### ISSUE TITLE
CSS文件构建不出来

### ISSUE THREAD

**Issue by MingXingTeam** [cloudcome/coolie#4]
文件结构以及配置内容如图：
![image](https://cloud.githubusercontent.com/assets/4523625/8948837/4fc4bd24-35de-11e5-9ebc-e014f95fe237.png)

*coolie.json中有配置css的路径*
*test.html引用了./static/test.css*

构建：coolie build

现象：
在dest目录下没有看到构建好的css文件   能否帮我看一下 谢谢~~

**Comment by cloudcome** [comment]
不好意思，现在才回复你，希望还可以帮到你。

```
<!--coolie-->
<link href="./static/style.css" rel="stylesheet">
<!--/coolie-->
```

被`<!--coolie-->`包裹的样式才会被管理。

**Comment by MingXingTeam** [comment]
非常感谢 我明天试试看
