### ISSUE TITLE
有没有类似seajs的alias或者paths的设置，每次写一串路径太麻烦

### ISSUE THREAD

**Issue by zct1989** [cloudcome/coolie#6]
有没有类似seajs的alias或者paths的设置，每次写一串路径太麻烦，虽然构建后没有路径，但是开发下的代码中,这种相对路径真希望有个别名
![image](https://cloud.githubusercontent.com/assets/4535888/11318423/86937710-908c-11e5-87af-7e1e825984c4.png)

**Comment by lntmny** [comment]
alias 和 paths 确实有这个需求的，暂时可以用别的方式代替一下，坐等功能上线：

因为这一类大多数都是会在文件里共用的第三方js文件，构建后都压缩到同一个文件里面，所以可以单独写一个模块来配置, 然后和模块压缩到一个文件里。

```js  
// file pm.js
define(function(require){
  export.$ = export.jQuery = require('/long/path/to/the/jquery_file.js');
  export.xxx =  require('/long/path/to/the/xxx.js');
});

```
使用的时候就 直接var $ = require('./pm').$;  可以暂时方便一点。

**Comment by cloudcome** [comment]
@zct1989 @lntmny  感谢反馈，待评估。
