### ISSUE TITLE
对于非模块化开发的项目，如何使用coolie？

### ISSUE THREAD

**Issue by k4124k** [cloudcome/coolie#7]
1.js的合并压缩 
2.css的合并压缩 
3.资源（js／css／img）的cdn发布

**Comment by cloudcome** [comment]
1、JS 的合并
http://coolie.ydr.me/guide/build-js/

2、CSS 的合并
http://coolie.ydr.me/guide/build-css/

3、CDN 发布
http://coolie.ydr.me/guide/coolie.config.js/#heading-2-18
可以指定 host，另外发布到 CDN，目前并未有工具集成在 coolie 里，我们内部使用的 [7niu 模块](https://www.npmjs.com/package/7niu)
