### ISSUE TITLE
你好 云淡然想问问有没有一个比较健全的实例demo工程呢~教程我能看懂就是不知道一个比较好的工程怎么搭建

### ISSUE THREAD

**Issue by FengZeming** [cloudcome/coolie#8]
也就是 目录到底怎么创建 如果是 跟后端java 交互 应该怎么做这些都不了解真的很希望您出一个比较健全的实例demo啊.coolie的指南里我看到有这个预留空间但是还没有内容.

**Comment by cloudcome** [comment]
关于 demo 示例，官网会陆续放出来的。敬请期待。

**Comment by cloudcome** [comment]
@FengZeming 官网 <http://coolie.ydr.me/>
